name: 'spotify'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - pip
  - matplotlib>=3.2.2
  - scikit-learn>=1.0
  - pandas>=1.3.*
  - requests>=2.24.0
  - altair 
  - graphviz
  - python-graphviz
  - lightgbm
  - py-xgboost==1.3.0
  - imbalanced-learn
  - pip:
    - mglearn
    - psutil>=5.7.2
    - rpy2
    - otter-grader